### ISSUE TITLE
remove small objects

### ISSUE THREAD

**Issue by LiheYoung** [Jia-Research-Lab/PFENet#11]
Thanks for sharing your work! 
I noticed that you remove all objects whose area are smaller than 2x32x32, following the practice of OSLSM. However, in some recent works, such as PANet(ICCV'19) and CANet(CVPR'19), they include all objects in their source code whatever their size is. So I am wondering whether it is somewhat unfair to compare with these methods directly? Or are there any details that I have neglected?

**Comment by tianzhuotao** [comment]
Hi,

Thank you for being interested in our work.

The preprocessed ground truth images of CANet are actually processed by the scripts of OSLSM and therefore the small objects are also removed in the project of CANet (we have confirmed with the authors of CANet before we submit our paper).

Also, I think it is okay to follow OSLSM to screen out small objects (we only remove them for support samples) because OSLSM is the first paper that proposes the setting of few-shot segmentation. 

Frankly speaking, it is hard to keep all papers to have the same configuration. If you want to have a comparison, you can try to remove the small objects using the repo of PANet to see the performance gap it causes to the model.

Thank you and hope my explanation is helpful.

**Comment by LiheYoung** [comment]
I think it is more practical to only remove them for support samples. Thanks for your explanation!

**Comment by LiheYoung** [comment]
Sorry to bother you again. But do you mean CANet removes small objects in both support and query set?

**Comment by tianzhuotao** [comment]
@LiheYoung I think the small objects are removed in CANet. However, from my perspective, we do not want to alter the data split for validation, even if some objects are small and hard for models to identify, therefore we only remove them from support samples.

**Comment by LiheYoung** [comment]
@tianzhuotao  Thanks for your explanation!

**Comment by LiheYoung** [comment]
I take a closer look at the dataloading process.

It seems that if an image doesn't contain any objects larger than 2x32x32, it will be removed from the data list. This image will never be selected during training or testing. And the small query objects in these removed images will never be sampled. Therefore, actually, it still removes a portion of small query objects, which may bring slight better performance.

Is there anything I misunderstand? Thanks!

**Comment by tianzhuotao** [comment]
@LiheYoung 

Thank you for mentioning it!

I overlooked this point when I reviewed my code. Yes, a portion of small objects in the query set has been excluded in my implementation, which causes a little improvement on average in my case. 

However, this repo can achieve higher performance than the results reported in my original paper (see [**this issue**](https://github.com/Jia-Research-Lab/PFENet/issues/6)). Of course, for a fair comparison, you can accordingly modify my code to be the same as that in your setting.

Thank you again! Please drop me a message if you have further questions.

**Comment by LiheYoung** [comment]
@tianzhuotao Thanks for your reply!

**Comment by cty21995** [comment]
![image](https://user-images.githubusercontent.com/107451143/173484500-581b9518-3205-4ec3-9e8b-93000a6fe009.png)
Why my test result of moiu is 0

**Comment by YooAoo** [comment]
If my picture is only 128*128 size, can I reduce this value?
